FitnessTracker/Controllers/AthleteController.cs
using FitnessTracker.Core.Contracts;
using FitnessTracker.Core.Extensions;
using FitnessTracker.Core.Models.Athlete;
using FitnessTracker.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FitnessTracker.Controllers
{
	[Authorize]
    public class AthleteController : Controller
    {
        private readonly IAthleteService service;
        private readonly IGymService gymService;

        public AthleteController(IAthleteService _service, IGymService _gymService)
        {
            service = _service;
            gymService = _gymService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await service.GetAthlete(User.Id());

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id, string information)
        {
            var model = await service.FindByIdAsync(id);

            if(model == null)
            {
                return NotFound();
            }

            if(information != model.GetAthleteInformation())
            {
                return BadRequest();
            }

            string userId = User.Id();

            bool userIsAthlete = await service.CheckUserId(userId, id);

            if (userIsAthlete == false)
            {
                return Unauthorized();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AthleteDetailsEditFormModel athleteDetails)
        {
            if(!ModelState.IsValid)
            {
                AthleteDetailsEditFormModel model = new AthleteDetailsEditFormModel() 
                {
                    Id = athleteDetails.Id,
                    FirstName = athleteDetails.FirstName,
                    LastName = athleteDetails.LastName,
                    Age = athleteDetails.Age,
                    Weight = athleteDetails.Weight,
                    Height = athleteDetails.Height
                };

                return View(model);
            }

            await service.EditDetailsAsync(athleteDetails);
            await service.SaveAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

FitnessTracker/Controllers/WorkoutController.cs
using FitnessTracker.Core.Contracts;
using FitnessTracker.Core.Models.Workout;
using FitnessTracker.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace FitnessTracker.Controllers
{
	[Authorize]
	public class WorkoutController : Controller
	{
		private readonly IWorkoutService service;
		private readonly IAthleteGymService athleteGymService;

		public WorkoutController(IWorkoutService _service, IAthleteGymService _athleteGymService)
		{
			service = _service;
			athleteGymService = _athleteGymService;
		}

		[HttpGet]
		public async Task<IActionResult> AddWorkout()
		{
			var model = new WorkoutFormModel();

			List<WorkoutIntensitiesFormModel> workoutData = new List<WorkoutIntensitiesFormModel>();

			if (TempData["WorkoutData"] is string json)
			{
				workoutData = JsonSerializer.Deserialize<List<WorkoutIntensitiesFormModel>>(json);

				TempData.Keep("WorkoutData");
			}

			model.WorkoutIntensities = workoutData;

			var exercises = await service.GetExercises();

			var userEmail = User.Email();

			var athleteId = await athleteGymService.GetAthleteId(userEmail);

			var gyms = await service.GetGyms(athleteId);

			ViewBag.WorkoutData = workoutData;
			ViewBag.Exercises = exercises;
			ViewBag.Gyms = gyms;

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> AddWorkout(WorkoutFormModel model)
		{
			if (TempData["WorkoutData"] is string json)
			{
				List<WorkoutIntensitiesFormModel> workoutData = JsonSerializer.Deserialize<List<WorkoutIntensitiesFormModel>>(json);

				model.WorkoutIntensities = workoutData.ToList();
			}

			var userEmail = User.Email();

			var athleteId = await athleteGymService.GetAthleteId(userEmail);

			if (!ModelState.IsValid)
			{
				model = new WorkoutFormModel();

				List<WorkoutIntensitiesFormModel> workoutData = new List<WorkoutIntensitiesFormModel>();

				if (TempData["WorkoutData"] is string data)
				{
					workoutData = JsonSerializer.Deserialize<List<WorkoutIntensitiesFormModel>>(data);

					TempData.Keep("WorkoutData");
				}

				var exercises = await service.GetExercises();

				var gyms = await service.GetGyms(athleteId);

				ViewBag.WorkoutData = workoutData;
				ViewBag.Exercises = exercises;
				ViewBag.Gyms = gyms;

				return View(model);
			}

			TempData.Clear();

			await service.CreateWorkout(model, athleteId);

			return RedirectToAction("Index", "Athlete");
		}

		[HttpPost]
		[IgnoreAntiforgeryToken]
		public IActionResult AddExercise(WorkoutIntensitiesFormModel model)
		{
			if (!ModelState.IsValid)
			{
				return View(model);
			}

			if (TempData.ContainsKey("WorkoutData"))
			{
				string json = string.Empty;

				if (TempData["WorkoutData"] is string data)
				{
					json = data;
				}

				List<WorkoutIntensitiesFormModel> workoutData = JsonSerializer.Deserialize<List<WorkoutIntensitiesFormModel>>(json);

				workoutData.Add(model);

				json = JsonSerializer.Serialize<List<WorkoutIntensitiesFormModel>>(workoutData);

				TempData["WorkoutData"] = json;
			}
			else
			{
				List<WorkoutIntensitiesFormModel> workoutData = new List<WorkoutIntensitiesFormModel>();

				workoutData.Add(model);

				string json = JsonSerializer.Serialize<List<WorkoutIntensitiesFormModel>>(workoutData);

				TempData["WorkoutData"] = json;
			}

			return RedirectToAction(nameof(AddWorkout));
		}
	}
}

FitnessTracker/Views/Athlete/Edit.cshtml
@model AthleteDetailsEditFormModel

@{
	ViewBag.Title = "Edit Your Personal Details.";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

@if (!ViewData.ModelState.IsValid && ViewData.ModelState["Error"] != null)
{
	<div class="alert alert-danger" role="alert">
		@ViewData.ModelState["Error"].Errors.First().ErrorMessage
	</div>
}
<hr />
<form method="post">
	<div class="form-group">
		<label asp-for="FirstName"></label>
		<input asp-for="FirstName" class="form-control" type="text" placeholder="Firs name.">
		<span asp-validation-for="FirstName" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="LastName"></label>
		<input asp-for="LastName" class="form-control" type="text" placeholder="Last name.">
		<span asp-validation-for="LastName" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Age"></label>
		<input asp-for="Age" class="form-control" type="text" placeholder="Age">

		<span asp-validation-for="Age" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Height"></label>
		<input asp-for="Height" class="form-control" type="text" placeholder="Height">
		<span asp-validation-for="Height" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Weight"></label>
		<input asp-for="Weight" class="form-control" type="text" placeholder="Weight">
		<span asp-validation-for="Weight" class="text-danger"></span>
	</div>
	<div>
		<p></p>
	</div>
	<div>
		<div class="d-grid gap-5 d-md-flex justify-content-md-center">
			<input class="btn btn-light btn-outline-dark btn-toolbar" type="submit" value="Save" />
		</div>
	</div>
</form>

@section Scripts {
	<partial-name ="_ValidationScriptsPartial" />
}

FitnessTracker/Views/Athlete/Index.cshtml
@model AthleteViewModel

@{
	ViewBag.Title = $"Welcome to your home page, {Model.FirstName} {Model.LastName}";
}

<h4 class="text-center">@ViewBag.Title</h4>
<hr />
<div class="flex-row justify-content-start">
    <div class="col">
        <div class="card" style="max-width: 18rem;">
            <div class="card-header">
                <svg class="bd-placeholder-img card-img-top" width="100%" height="180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Image cap" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#868e96"></rect>
                    <text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image cap</text>
                </svg>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Hight: @Model.Height</li>
                <li class="list-group-item">Weight: @Model.Weight</li>
                <li class="list-group-item">Age: @Model.Age</li>
            </ul>
            <div class="card-footer">
                <a class="btn btn-light btn-outline-dark btn-sm" asp-controller="Athlete" asp-action="Edit" asp-route-id="@Model.Id" asp-route-information="@Model.GetAthleteInformation()">Edit details</a>
            </div>
        </div>
    </div>
    <div class="col">
        <hr />
        <h4 class="text-lg-center">Gym memberships.</h4>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Start date</th>
                    <th scope="col">Expire date</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var gym in Model.AthletesGym)
                {
                    <tr>
                        <td>@gym.GymName</td>
                        <td>@gym.StartDate.ToShortDateString()</td>
                        <td>
                            @if (gym.EndDate < DateTime.Now)
                            {
                                <p class="text-danger">@gym.EndDate.ToShortDateString()</p>
                            }
                            else
                            {
                                @gym.EndDate.ToShortDateString()
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <hr />
    </div>
</div>
<div class="d-grid gap-5 d-md-flex justify-content-md-between">
    <h3 class="text-center">Workouts</h3>
    <a class="btn btn-light btn-outline-dark btn-toolbar" asp-controller="Workout" asp-action="AddWorkout">Add Workout</a>
</div>
<p></p>
<div></div>
@foreach (var workout in Model.Workouts)
{
    <div class="card">
        <div class="card-header">
            @workout.WorkoutType ; Date of workout: @workout.Date ; Performed at gym: @workout.GymName
        </div>
        <div class="card-body">
        <ul class="list-group list-group-flush">
            @foreach (var exercise in workout.Exercises)
            {
                <li class="list-group-item">Exercise name: @exercise.ExerciseName ; Exercise Sets: @exercise.Sets ; Exercise Repetitions: @exercise.Repetitions ; Average time per set: @exercise.Seconds</li>
            }
        </ul>
        </div>
    </div>
}