FitnessTracker/Controllers/AthleteGymController.cs
using FitnessTracker.Core.Contracts;
using FitnessTracker.Core.Extensions;
using FitnessTracker.Core.Models.AthleteGym;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static FitnessTracker.Core.Constants.ModelStateErrors;

namespace FitnessTracker.Controllers
{
	[Authorize]
    public class AthleteGymController : Controller
    {
		private readonly IAthleteGymService service;
		private readonly IGymService gymService;

        public AthleteGymController(IAthleteGymService _service, IGymService _gymService)
        {
            service = _service;
			gymService = _gymService;
        }

        [HttpGet]
		public async Task<IActionResult> Renew(int athleteId, int gymId, string information)
		{

			var gym = await gymService.GetGymAsync(gymId);

			var gymInformation = gym.GetGymInformation();

			if (information != gymInformation)
			{
				return BadRequest();
			}

			var athleteIsMember = await service.AthleteIsMember(athleteId, gymId);

			if (athleteIsMember == false)
			{
				return NotFound();
			}

			var model = new GymMembershipRenewFormModel()
			{
				AthleteId = athleteId,
				GymId = gymId,
				Name = gym.Name,
				Address = gym.Address
			};

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Renew(GymMembershipRenewFormModel model)
		{
			if (!ModelState.IsValid)
			{
				model = new GymMembershipRenewFormModel()
				{
					AthleteId = model.AthleteId,
					GymId = model.GymId
				};

				return View(model);
			}

			await service.RenewAsync(model);

			return RedirectToAction("Details", "Gym", new { id = model.GymId, information = model.GetGymInformation() });;
		}

		[HttpGet]
		public async Task<IActionResult> AddMember(int gymId, string information)
		{
			var gym = await gymService.GetGymAsync(gymId);

			var gymInformation = gym.GetGymInformation();

			if (information != gymInformation)
			{
				return BadRequest();
			}

			var newMember = new NewMembershipFormModel()
			{
				GymId = gymId,
				Name = gym.Name,
				Address = gym.Address
			};

			return View(newMember);
		}

		[HttpPost]
		public async Task<IActionResult> AddMember(NewMembershipFormModel model)
		{
			int gymId = model.GymId;

			if (await service.AthleteExists(model.UserEmail) == false)
			{
				return NotFound();
			}

			var athleteId = await service.GetAthleteId(model.UserEmail);

			if(athleteId <= 0)
			{
				ModelState.AddModelError(ErrorKeyWhenThereAreTwoIdenticalEmails, MultipleUsersWithSameEmail);

				model = new NewMembershipFormModel()
				{
					GymId = gymId
				};

				return View(model);
			}

			if (!ModelState.IsValid)
			{
				model = new NewMembershipFormModel()
				{
					GymId = gymId
				};

				return View(model);
			}

			await service.AddNewMember(model, athleteId);

			return RedirectToAction("Details", "Gym", new { id = model.GymId, information = model.GetGymInformation() });
		}
	}
}

FitnessTracker/Controllers/GymController.cs
using FitnessTracker.Core.Contracts;
using FitnessTracker.Core.Extensions;
using FitnessTracker.Core.Models.Gym;
using FitnessTracker.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FitnessTracker.Controllers
{
	[Authorize]
	public class GymController : Controller
	{
		private readonly IGymService service;

		public GymController(IGymService _service)
		{
			service = _service;
		}

		[AllowAnonymous]
		[HttpGet]
		public async Task<IActionResult> All()
		{
			var model = await service.GetAllPublicAsync();

			return View(model);
		}

		[AllowAnonymous]
		[HttpGet]
		public async Task<IActionResult> Details(int id, string information)
		{
			if (await service.GymExistsAsync(id) == false)
			{
				return NotFound();
			}
			
			var userId = User.Id();

			var model = await service.GetGymAsync(id);

			if (await service.GymIsPublic(id) == false && model.OwnerId != userId)
			{
				return BadRequest();
			}

			if (information != model.GetGymInformation())
			{
				return BadRequest();
			}

			ViewBag.UserId = userId;

			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> MyGym()
		{
			var userId = User.Id();

			var gym = await service.GetGymByUserIdAsync(userId);

			if(gym.OwnerId != userId)
			{
				return Unauthorized();
			}

			return RedirectToAction(nameof(Details), new { id = gym.Id, information = gym.GetGymInformation() });
		}

		[HttpGet]
		public async Task<IActionResult> Edit(int id, string information)
        {
            if (await service.GymExistsAsync(id) == false)
            {
                return BadRequest();
            }

            var gymDetails = await service.GetGymAsync(id);

			var userId = User.Id();

			if(gymDetails.OwnerId != userId)
			{
				return Unauthorized();
			}

			var model = new GymDetailsFormViewModel()
			{
				Id = gymDetails.Id,
				Name = gymDetails.Name,
				Address = gymDetails.Address,
				PhoneNumber = gymDetails.PhoneNumber,
				PricePerMonth = decimal.Parse(gymDetails.PricePerMonth)
			};

			if(information != model.GetGymInformation())
			{
				return BadRequest();
			}

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(GymDetailsFormViewModel model)
		{
			int gymId = model.Id;

			var gym = await service.GetGymDetailsAsync(gymId);

			if (!ModelState.IsValid)
			{
				model = new GymDetailsFormViewModel()
				{
					Id = gymId,
					Name = gym.Name,
					Address = gym.Address,
					PhoneNumber = gym.PhoneNumber,
					PricePerMonth = gym.PricePerMonth
				};

				return View(model);
			}

			gymId = await service.ChangeGymDetailsAsync(model);

			return RedirectToAction(nameof(Details), new { id = gymId, information = model.GetGymInformation() });
		}

		[HttpPost]
		public async Task<IActionResult> ChangeGymType(GymTypeFormModel model)
		{
			if (!ModelState.IsValid)
			{
				return View(model);
			}

			await service.ChangeGymTypeAsync(model);

			return RedirectToAction(nameof(Details), new { id = model.Id, information = model.GetGymInformation() });
		}
    }
}

FitnessTracker/Views/Gym/All.cshtml
@model List<GymViewModel>

@{
	ViewBag.Title = "Gyms";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="accordion" id="accordionExample">
    @foreach(var item in Model)
    {
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                    @item.Name
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                <svg class="bd-placeholder-img float-md-top" width="100%" height="210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Responsive floated image" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#868e96"></rect>
                    <text x="50%" y="50%" fill="#dee2e6" dy=".3em">Responsive floated image</text>
                </svg>
                <div class="accordion-body">
                    <p class="card-text text-warp text-truncate" style="max-width: 500px">Address: @item.Address</p>
                    <p class="card-text text--warp text-truncate" style="max-width: 500px">Phone number: @item.PhoneNumber</p>
                    <p class="card-text text--warp text-truncate" style="max-width: 500px">Price per month: @item.PricePerMonth lv.</p>
                </div>
                <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                    <a class="btn btn-light btn-outline-dark btn-toolbar" asp-controller="Gym" asp-action="Details" asp-route-id="@item.Id" asp-route-information="@item.GetGymInformation()">Details</a>
                </div>
            </div>
        </div>
    }
</div>

FitnessTracker/Views/Gym/Details.cshtml
@model GymDetailViewModel
@inject IAntiforgery AntiForgery

<h2 class="text-center">@Model.Name</h2>
<hr />

<div class="container text-center">
    <div class="rol">
        <svg class="bd-placeholder-img float-md-top" width="100%" height="210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Responsive floated image" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#868e96"></rect>
            <text x="50%" y="50%" fill="#dee2e6" dy=".3em">Responsive floated image</text>
        </svg>
        <p></p>
    </div>
    <div class="row">
        <div class="col">
            <div class="d-grid gap-2 d-md-flex justify-content-md-between">
                <h6 class="text">Owner: @Model.Owner.FirstName @Model.Owner.LastName</h6>
                <h6 class="text">Gym type: @Model.GymType</h6>
                <h6 class="text">Price per month: @Model.PricePerMonth lv.</h6>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-between">
                <h6 class="text">Address: @Model.Address</h6>
                <h6 class="text">Phone number: @Model.PhoneNumber</h6>
            </div>
        </div>
        <div class="col-2">
            @if (Model.OwnerId == ViewBag.UserId)
            {
                <div class="btn-group-vertical" role="rowgroup" aria-label="Vertical button group">
                        <a class="btn btn-light btn-outline-dark btn-toolbar" asp-controller="Gym" asp-action="Edit" asp-route-id="@Model.Id" asp-route-information="@Model.GetGymInformation()">Edit gym details</a>
                        <p></p>
                        <button type="button" class="btn btn-light btn-outline-dark" data-bs-toggle="modal" data-bs-target="#changeGymTypeModal">Change gym type</button>
                </div>
            }
        </div>
    </div>
</div>
<hr />
<div class="container">
@if(Model.OwnerId == ViewBag.UserId)
{
    <div class="d-grid gap-5 d-md-flex justify-content-md-between">
        <p></p>
        <h2 class="text-center">Members</h2>
        <a class="btn btn-light btn-outline-dark btn-toolbar" asp-controller="AthleteGym" asp-action="AddMember" 
            asp-route-gymId="@Model.Id" asp-route-information="@Model.GetGymInformation()">Add member</a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Hight</th>
                <th scope="col">Weight</th>
                <th scope="col">Start date</th>
                <th scope="col">Expire date</th>
                <th scope="col">Renew</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var member in Model.Members)
            {
                <tr>
                    <td>@member.Name</td>
                    <td>@member.Height</td>
                    <td>@member.Weight</td>
                    <td>@member.StartDate.ToShortDateString()</td>
                    <td>
                        @if (member.EndDate < DateTime.Now)
                        {
                            <p class="text-danger">@member.EndDate.ToShortDateString()</p>
                        }
                        else
                        {
                            @member.EndDate.ToShortDateString()
                        }
                    </td>
                    <td>
                        <a class="btn btn-light btn-outline-dark btn-toolbar" asp-controller="AthleteGym" asp-action="Renew" asp-route-athleteId="@member.MemberId"
                            asp-route-gymId="@Model.Id" asp-route-information="@Model.GetGymInformation()">Renew</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
</div>
<div class="modal fade" id="changeGymTypeModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="changeGymTypeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="changeGymTypeModalLabel">Change Gym Type</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="gymTypeForm">
                    <div class="mb-3">
                        <label for="type" class="form-label">Gym Type</label>
                        <select for="type" class="form-select" id="type" name="type">
                            @foreach (var item in Enum.GetNames(typeof(GymType)))
                            {
                                <option value="@item">@item.ToString()</option>
                            }
                        </select>
                    </div>
                    <div class="form-group visually-hidden">
                        <label for="id" class="form-label">Id</label>
                        <input for="id" type="text" class="form-control" id="id" name="id" value="@Model.Id" readonly>
                    </div>
                    <div class="form-group visually-hidden">
                        <label for="name" class="form-label">Name</label>
                        <input for="name" type="text" class="form-control" id="name" name="name" value="@Model.Name" readonly>
                    </div>
                    <div class="form-group visually-hidden">
                        <label for="address" class="form-label">Address</label>
                        <input for="address" type="text" class="form-control" id="address" name="address" value="@Model.Address" readonly>
                    </div>
                    <div>
                        <input type="hidden" id="antiForgeryToken" value="@AntiForgery.GetAndStoreTokens(Context).RequestToken" />
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary btn-outline-dark">Apply Change</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
	<partial-name ="_ValidationScriptsPartial" />
	<script src="~/js/jquery.change.gym.type.js"></script>
	<script>
		var changeGymTypeUrl = '@Url.Action("ChangeGymType", "Gym")';
	</script>
}

FitnessTracker/Views/Gym/Edit.cshtml
@model GymDetailsFormViewModel

@{
	ViewBag.Title = "Edit Your Gym Details.";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

@if (!ViewData.ModelState.IsValid && ViewData.ModelState["Error"] != null)
{
	<div class="alert alert-danger" role="alert">
		@ViewData.ModelState["Error"].Errors.First().ErrorMessage
	</div>
}
<hr />
<form method="post">
	<div class="form-group">
		<label asp-for="Name"></label>
		<input asp-for="Name" class="form-control" type="text" placeholder="Gym Name.">
		<span asp-validation-for="Name" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Address"></label>
		<input asp-for="Address" class="form-control" type="text" placeholder="Gym Address.">
		<span asp-validation-for="Address" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="PhoneNumber"></label>
		<input asp-for="PhoneNumber" class="form-control" type="text" placeholder="Gym Phone Number.">
		<span asp-validation-for="PhoneNumber" class="text-danger"></span>
	</div><div class="form-group">
		<label asp-for="PricePerMonth"></label>
		<input asp-for="PricePerMonth" class="form-control" type="text">
		<span asp-validation-for="PricePerMonth" class="text-danger"></span>
	</div>
	<div>
		<p></p>
	</div>
	<div>
		<div class="d-grid gap-5 d-md-flex justify-content-md-center">
			<input class="btn btn-light btn-outline-dark btn-toolbar" type="submit" value="Save" />
		</div>
	</div>
</form>

@section Scripts {
	<partial-name ="_ValidationScriptsPartial" />
}